#ASP.NET
trigger:
- circleci-project-setup

pool:
  vmimage: 'ubuntu-latest'

variable:
  solution: '**/*.slnx'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredential: true
  submodules: true

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/.*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Tests'
  inputs:
    command: 'test'
    projects: '**/*Test/*.csproj'
    configuration: '--no-build --configuration $(buildConfiguration)'

